server:
  port: 1234

spring:
  application:
    name: transaction_with_aop

  datasource:
    url: jdbc:postgresql://localhost:5432/project?currentSchema=transaction_with_aop
    username: postgres
    password: 2210
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha                # Tag?larni alifbo tartibida ko?rsatadi
    doc-expansion: none               # Swagger?da barcha bo?limlar yopiq holda chiqadi (collapsed)
    try-it-out-enabled: true          # "Try it out" tugmasini o?chiradi (foydalanuvchi swagger orqali API chaqira olmaydi)
    default-model-expand-depth: 10    # Model (schema) larni nechta chuqurlikda expand qilishini belgilaydi
    operations-sorter: method         # metodlarni tartib bilan ko?rsatadi (GET, POST, PUT...)
    display-request-duration: true    # har bir request qancha vaqt olganini ko?rsatadi
